on: [push, pull_request]

name: ci

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          deno-version: 16

      - name: Install
        run: |
          npm install

      - name: Test
        run: |
          npm run test

      - name: Build
        run: |
          npm run build

      - uses: actions/upload-artifact@v2
        if: runner.os == 'linux'
        with:
          name: dist
          path: ./dist

  release:
    name: Release to Github
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'axetroy/fata'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./package.json
          token: ${{ secrets.NPM_TOKEN }}
